extends RefCounted

const TEXT := {
    "zh_hans": {
        "settings.section.diagnostics": "诊断",
        "settings.section.compatibility": "兼容性",
        "settings.section.advanced": "高级开发工具",
        "settings.diagnostic_profile": "诊断模式",
        "settings.diagnostic_profile_desc": "统一控制要采集的证据范围；Baseline 开销低，Full 开销高且仅建议短时使用",
        "settings.debug_overlay": "调试悬浮信息",
        "settings.debug_overlay_desc": "在游戏画面上显示简要或详细的实时性能摘要",
        "settings.error_dialog_logs": "错误附带上下文",
        "settings.error_dialog_logs_desc": "真正异常的弹窗附带最近 20 行日志，便于直接判断异常边界",
        "settings.plugin_load_mode": "插件加载范围",
        "settings.plugin_load_mode_desc": "核心兼容仅加载常用插件；完整兼容保留旧版全量注册路径",
        "settings.plugin_load.core": "核心兼容",
        "settings.plugin_load.all": "完整兼容",
        "settings.mock": "缺失插件兼容",
        "settings.mock_desc": "缺失插件时返回兼容对象。关闭后会暴露真实缺失错误，适合定位兼容问题。",
        "settings.advanced_desc": "以下开关只对本次运行有效，重启后自动关闭。详细追踪会增加日志量和帧耗时。",
        "settings.plugin_trace": "插件调用追踪（高开销，30 秒）",
        "settings.plugin_trace_desc": "临时记录所有原生插件调用与失败边界",
        "settings.console_log": "旧版控制台日志文件",
        "settings.console_log_desc": "本次运行将引擎输出额外写入本地日志文件",
        "settings.trace_log": "完整 Trace 日志（高开销，30 秒）",
        "settings.trace_log_desc": "临时启用最详细的 spdlog trace 输出",
        "settings.export_tjs": "导出 TJS 脚本",
        "settings.export_tjs_desc": "本次运行在加载 XP3 时导出反汇编脚本；会增加存储开销",
        "profile.off": "关闭",
        "profile.baseline": "基础",
        "profile.input": "输入",
        "profile.render": "渲染",
        "profile.storage": "存储",
        "profile.script": "脚本",
        "profile.audio": "音频",
        "profile.video": "视频",
        "profile.plugin": "插件",
        "profile.system": "系统",
        "profile.full": "完整（高开销）",
        "overlay.off": "关闭",
        "overlay.summary": "简要",
        "overlay.detail": "详细",
        "debug.title": "运行时调试",
        "debug.open": "打开运行时调试抽屉",
        "debug.tab.overview": "概览",
        "debug.tab.events": "事件",
        "debug.tab.logs": "日志",
        "debug.tab.input": "输入",
        "debug.tab.plugins": "插件",
        "debug.action.mark": "标记问题",
        "debug.action.slow": "捕获下个慢帧",
        "debug.action.snapshot": "状态快照",
        "debug.action.screenshot": "截图",
        "debug.action.self_check": "自检",
        "debug.action.copy": "复制摘要",
        "debug.action.export": "导出 ZIP",
        "debug.filter.subsystem": "按子系统筛选",
        "debug.filter.search": "搜索日志",
        "debug.logs.pause": "暂停",
        "debug.logs.resume": "继续",
        "debug.logs.copy": "复制",
        "debug.logs.clear": "清空",
        "debug.marker.user_issue": "一般问题", "debug.marker.slow_frame": "慢帧", "debug.marker.input_issue": "输入问题", "debug.marker.visual_issue": "画面问题", "debug.marker.audio_issue": "音频问题", "debug.marker.loading_issue": "加载问题",
        "debug.filter.value.all": "全部", "debug.filter.value.info": "信息", "debug.filter.value.warning": "警告", "debug.filter.value.error": "错误",
        "debug.value.yes": "是", "debug.value.no": "否",
        "debug.input.visualize": "在画面上显示触点与命中位置",
        "debug.input.last": "最近事件",
        "debug.input.target": "命中控件",
        "debug.advanced.plugin": "插件追踪",
        "debug.advanced.full": "完整追踪",
        "debug.advanced.console": "控制台文件",
        "debug.advanced.tjs": "TJS 导出",
        "debug.metric.frame": "帧率",
        "debug.metric.renderer": "渲染器",
        "debug.metric.directory": "会话目录",
        "debug.overview.percentiles": "P50 %.2f ms  P95 %.2f ms  P99 %.2f ms  最大 %.2f ms",
        "debug.overview.phases": "C++ tick %.2f ms  Godot 更新 %.2f ms  整帧 %.2f ms",
        "debug.overview.render": "纹理 %s  画布 %s  回退 %s",
        "debug.overview.memory": "内存：应用 %s  系统空闲/总量 %s / %s  缓存 %s",
        "debug.overview.memory_extended": "峰值 %s  可用额度 %s  Godot %s  GPU（估算）%s（纹理 %s / 缓冲 %s）",
        "debug.overview.counts": "错误 %d  丢弃事件 %d  问题标记 %d",
        "debug.input.primary_counts": "接收 %d  转发 %d  阻塞 %d", "debug.input.secondary_counts": "节流 %d  忙碌 %d  越界 %d  抑制 %d", "debug.input.active_count": "活动指针 %d",
        "debug.plugins.counts": "加载 %d  失败 %d  回退 %d  缺失 %d", "debug.plugins.calls": "方法调用 %d  属性调用 %d", "debug.plugins.loaded": "已加载：%s", "debug.plugins.failed": "失败：%s", "debug.plugins.fallback": "回退：%s", "debug.plugins.missing": "缺失：%s",
        "debug.empty.events": "当前筛选条件下没有事件",
        "debug.empty.logs": "当前筛选条件下没有日志",
        "debug.overhead": "采集开销",
        "debug.overhead.low": "低",
        "debug.overhead.medium": "中",
        "debug.overhead.high": "高",
        "debug.result.marked": "问题已标记：%s（将继续收集后 5 秒）",
        "debug.result.marker_limit": "本次会话已达到 %s 个问题标记上限",
        "debug.result.snapshot": "状态快照已保存：%s",
        "debug.result.screenshot": "截图已保存：%s",
        "debug.result.exported": "诊断包已导出：%s",
        "debug.result.copied": "诊断摘要已复制",
        "debug.result.slow_armed": "已等待下一个超过阈值的慢帧",
        "debug.result.self_check": "自检：%s",
        "debug.result.unavailable": "当前没有活动的诊断会话",
    },
    "zh_hant": {
        "settings.section.diagnostics": "診斷", "settings.section.compatibility": "相容性", "settings.section.advanced": "進階開發工具",
        "settings.diagnostic_profile": "診斷模式", "settings.diagnostic_profile_desc": "統一控制要收集的證據範圍；Baseline 開銷低，Full 開銷高且僅建議短時間使用",
        "settings.debug_overlay": "除錯浮動資訊", "settings.debug_overlay_desc": "在遊戲畫面上顯示簡要或詳細的即時效能摘要",
        "settings.error_dialog_logs": "錯誤附帶內容", "settings.error_dialog_logs_desc": "真正異常的對話框附帶最近 20 行日誌，以便直接判斷異常邊界",
        "settings.plugin_load_mode": "外掛載入範圍", "settings.plugin_load_mode_desc": "核心相容只載入常用外掛；完整相容保留舊版全量註冊路徑",
        "settings.plugin_load.core": "核心相容", "settings.plugin_load.all": "完整相容",
        "settings.mock": "缺失外掛相容", "settings.mock_desc": "缺失外掛時回傳相容物件。關閉後會暴露真實缺失錯誤，適合定位相容問題。",
        "settings.advanced_desc": "以下開關只對本次執行有效，重新啟動後自動關閉。詳細追蹤會增加日誌量和幀耗時。",
        "settings.plugin_trace": "外掛呼叫追蹤（高開銷，30 秒）", "settings.plugin_trace_desc": "暫時記錄所有原生外掛呼叫與失敗邊界",
        "settings.console_log": "舊版主控台日誌檔", "settings.console_log_desc": "本次執行將引擎輸出額外寫入本機日誌檔",
        "settings.trace_log": "完整 Trace 日誌（高開銷，30 秒）", "settings.trace_log_desc": "暫時啟用最詳細的 spdlog trace 輸出",
        "settings.export_tjs": "匯出 TJS 腳本", "settings.export_tjs_desc": "本次執行載入 XP3 時匯出反組譯腳本；會增加儲存開銷",
        "profile.off": "關閉", "profile.baseline": "基礎", "profile.input": "輸入", "profile.render": "渲染", "profile.storage": "儲存", "profile.script": "腳本", "profile.audio": "音訊", "profile.video": "視訊", "profile.plugin": "外掛", "profile.system": "系統", "profile.full": "完整（高開銷）",
        "overlay.off": "關閉", "overlay.summary": "簡要", "overlay.detail": "詳細",
        "debug.title": "執行時除錯", "debug.open": "開啟執行時除錯抽屜", "debug.tab.overview": "概覽", "debug.tab.events": "事件", "debug.tab.logs": "日誌", "debug.tab.input": "輸入", "debug.tab.plugins": "外掛",
        "debug.action.mark": "標記問題", "debug.action.slow": "擷取下個慢幀", "debug.action.snapshot": "狀態快照", "debug.action.screenshot": "截圖", "debug.action.self_check": "自我檢查", "debug.action.copy": "複製摘要", "debug.action.export": "匯出 ZIP",
        "debug.filter.subsystem": "依子系統篩選", "debug.filter.search": "搜尋日誌", "debug.logs.pause": "暫停", "debug.logs.resume": "繼續", "debug.logs.copy": "複製", "debug.logs.clear": "清除",
        "debug.marker.user_issue": "一般問題", "debug.marker.slow_frame": "慢幀", "debug.marker.input_issue": "輸入問題", "debug.marker.visual_issue": "畫面問題", "debug.marker.audio_issue": "音訊問題", "debug.marker.loading_issue": "載入問題",
        "debug.filter.value.all": "全部", "debug.filter.value.info": "資訊", "debug.filter.value.warning": "警告", "debug.filter.value.error": "錯誤", "debug.value.yes": "是", "debug.value.no": "否",
        "debug.input.visualize": "在畫面上顯示觸點與命中位置", "debug.input.last": "最近事件", "debug.input.target": "命中控制項",
        "debug.advanced.plugin": "外掛追蹤", "debug.advanced.full": "完整追蹤", "debug.advanced.console": "主控台檔案", "debug.advanced.tjs": "TJS 匯出",
        "debug.metric.frame": "幀率", "debug.metric.renderer": "渲染器", "debug.metric.directory": "工作階段目錄", "debug.empty.events": "目前篩選條件下沒有事件", "debug.empty.logs": "目前篩選條件下沒有日誌",
        "debug.overview.percentiles": "P50 %.2f ms  P95 %.2f ms  P99 %.2f ms  最大 %.2f ms", "debug.overview.phases": "C++ tick %.2f ms  Godot 更新 %.2f ms  整幀 %.2f ms", "debug.overview.render": "紋理 %s  畫布 %s  回退 %s", "debug.overview.memory": "記憶體：App %s  系統可用/總量 %s / %s  快取 %s", "debug.overview.memory_extended": "峰值 %s  可用額度 %s  Godot %s  GPU（估算）%s（紋理 %s / 緩衝 %s）", "debug.overview.counts": "錯誤 %d  丟棄事件 %d  問題標記 %d",
        "debug.input.primary_counts": "接收 %d  轉送 %d  阻擋 %d", "debug.input.secondary_counts": "節流 %d  忙碌 %d  越界 %d  抑制 %d", "debug.input.active_count": "作用中指標 %d",
        "debug.plugins.counts": "載入 %d  失敗 %d  回退 %d  缺失 %d", "debug.plugins.calls": "方法呼叫 %d  屬性呼叫 %d", "debug.plugins.loaded": "已載入：%s", "debug.plugins.failed": "失敗：%s", "debug.plugins.fallback": "回退：%s", "debug.plugins.missing": "缺失：%s",
        "debug.overhead": "收集開銷", "debug.overhead.low": "低", "debug.overhead.medium": "中", "debug.overhead.high": "高",
        "debug.result.marked": "問題已標記：%s（將繼續收集後 5 秒）", "debug.result.marker_limit": "此工作階段已達到 %s 個問題標記上限", "debug.result.snapshot": "狀態快照已儲存：%s", "debug.result.screenshot": "截圖已儲存：%s", "debug.result.exported": "診斷包已匯出：%s", "debug.result.copied": "診斷摘要已複製", "debug.result.slow_armed": "正在等待下一個超過門檻的慢幀", "debug.result.self_check": "自我檢查：%s", "debug.result.unavailable": "目前沒有作用中的診斷工作階段",
    },
    "en": {
        "settings.section.diagnostics": "Diagnostics", "settings.section.compatibility": "Compatibility", "settings.section.advanced": "Advanced Developer Tools",
        "settings.diagnostic_profile": "Diagnostic Mode", "settings.diagnostic_profile_desc": "Controls the evidence collected as one profile. Baseline is low overhead; Full is expensive and intended for short runs.",
        "settings.debug_overlay": "Debug Overlay", "settings.debug_overlay_desc": "Show a compact or detailed live performance summary over the game",
        "settings.error_dialog_logs": "Attach Error Context", "settings.error_dialog_logs_desc": "Attach the latest 20 log lines to real error dialogs to expose the first failing boundary",
        "settings.plugin_load_mode": "Plugin Load Scope", "settings.plugin_load_mode_desc": "Core Compatibility loads common plugins only; Full Compatibility keeps the legacy full registration path",
        "settings.plugin_load.core": "Core Compatibility", "settings.plugin_load.all": "Full Compatibility",
        "settings.mock": "Missing Plugin Compatibility", "settings.mock_desc": "Return compatibility objects for missing plugins. Disable to expose real missing-plugin errors.",
        "settings.advanced_desc": "These switches affect this run only and reset on restart. Detailed tracing increases log volume and frame time.",
        "settings.plugin_trace": "Plugin Call Trace (high, 30 sec)", "settings.plugin_trace_desc": "Temporarily record every native plugin call and failure boundary",
        "settings.console_log": "Legacy Console Log File", "settings.console_log_desc": "Also write engine output to a local log file for this run",
        "settings.trace_log": "Full Trace Log (high, 30 sec)", "settings.trace_log_desc": "Temporarily enable the most detailed spdlog trace output",
        "settings.export_tjs": "Export TJS Scripts", "settings.export_tjs_desc": "Export disassembled scripts while loading XP3 archives for this run; increases storage cost",
        "profile.off": "Off", "profile.baseline": "Baseline", "profile.input": "Input", "profile.render": "Render", "profile.storage": "Storage", "profile.script": "Script", "profile.audio": "Audio", "profile.video": "Video", "profile.plugin": "Plugin", "profile.system": "System", "profile.full": "Full (high overhead)",
        "overlay.off": "Off", "overlay.summary": "Summary", "overlay.detail": "Detailed",
        "debug.title": "Runtime Debugger", "debug.open": "Open runtime debug drawer", "debug.tab.overview": "Overview", "debug.tab.events": "Events", "debug.tab.logs": "Logs", "debug.tab.input": "Input", "debug.tab.plugins": "Plugins",
        "debug.action.mark": "Mark Issue", "debug.action.slow": "Capture Next Slow Frame", "debug.action.snapshot": "State Snapshot", "debug.action.screenshot": "Screenshot", "debug.action.self_check": "Self-check", "debug.action.copy": "Copy Summary", "debug.action.export": "Export ZIP",
        "debug.filter.subsystem": "Filter subsystem", "debug.filter.search": "Search logs", "debug.logs.pause": "Pause", "debug.logs.resume": "Resume", "debug.logs.copy": "Copy", "debug.logs.clear": "Clear",
        "debug.marker.user_issue": "General issue", "debug.marker.slow_frame": "Slow frame", "debug.marker.input_issue": "Input issue", "debug.marker.visual_issue": "Visual issue", "debug.marker.audio_issue": "Audio issue", "debug.marker.loading_issue": "Loading issue",
        "debug.filter.value.all": "All", "debug.filter.value.info": "Info", "debug.filter.value.warning": "Warning", "debug.filter.value.error": "Error", "debug.value.yes": "yes", "debug.value.no": "no",
        "debug.input.visualize": "Show touches and hit positions over the game", "debug.input.last": "Last event", "debug.input.target": "Hit control",
        "debug.advanced.plugin": "Plugin trace", "debug.advanced.full": "Full trace", "debug.advanced.console": "Console file", "debug.advanced.tjs": "TJS export",
        "debug.metric.frame": "Frame rate", "debug.metric.renderer": "Renderer", "debug.metric.directory": "Session directory", "debug.empty.events": "No events match the current filter", "debug.empty.logs": "No logs match the current filter",
        "debug.overview.percentiles": "P50 %.2f ms  P95 %.2f ms  P99 %.2f ms  Max %.2f ms", "debug.overview.phases": "C++ tick %.2f ms  Godot update %.2f ms  frame %.2f ms", "debug.overview.render": "Texture %s  Surface %s  Fallback %s", "debug.overview.memory": "Memory: app %s  system free/total %s / %s  cache %s", "debug.overview.memory_extended": "Peak %s  headroom %s  Godot %s  GPU (est.) %s (texture %s / buffer %s)", "debug.overview.counts": "Errors %d  Dropped events %d  Markers %d",
        "debug.input.primary_counts": "received %d  forwarded %d  blocked %d", "debug.input.secondary_counts": "throttled %d  busy %d  outside %d  suppressed %d", "debug.input.active_count": "active pointers %d",
        "debug.plugins.counts": "loaded %d  failed %d  fallback %d  missing %d", "debug.plugins.calls": "method calls %d  property calls %d", "debug.plugins.loaded": "loaded: %s", "debug.plugins.failed": "failed: %s", "debug.plugins.fallback": "fallback: %s", "debug.plugins.missing": "missing: %s",
        "debug.overhead": "Collection overhead", "debug.overhead.low": "low", "debug.overhead.medium": "medium", "debug.overhead.high": "high",
        "debug.result.marked": "Issue marked: %s (collecting 5 seconds after it)", "debug.result.marker_limit": "This session has reached its %s issue-marker limit", "debug.result.snapshot": "State snapshot saved: %s", "debug.result.screenshot": "Screenshot saved: %s", "debug.result.exported": "Diagnostic bundle exported: %s", "debug.result.copied": "Diagnostic summary copied", "debug.result.slow_armed": "Waiting for the next frame above the slow threshold", "debug.result.self_check": "Self-check: %s", "debug.result.unavailable": "No active diagnostic session",
    },
    "ja": {
        "settings.section.diagnostics": "診断", "settings.section.compatibility": "互換性", "settings.section.advanced": "高度な開発ツール",
        "settings.diagnostic_profile": "診断モード", "settings.diagnostic_profile_desc": "収集する証拠の範囲を一括指定します。Baseline は低負荷、Full は高負荷で短時間の使用向けです。",
        "settings.debug_overlay": "デバッグオーバーレイ", "settings.debug_overlay_desc": "ゲーム画面に簡易または詳細なリアルタイム性能情報を表示します",
        "settings.error_dialog_logs": "エラーにコンテキストを添付", "settings.error_dialog_logs_desc": "実際のエラーダイアログに直近 20 行のログを添付します",
        "settings.plugin_load_mode": "プラグイン読み込み範囲", "settings.plugin_load_mode_desc": "コア互換は一般的なプラグインのみ、完全互換は従来の全登録経路を使用します",
        "settings.plugin_load.core": "コア互換", "settings.plugin_load.all": "完全互換",
        "settings.mock": "不足プラグイン互換", "settings.mock_desc": "不足プラグインには互換オブジェクトを返します。無効にすると実際の不足エラーを確認できます。",
        "settings.advanced_desc": "以下は今回の実行だけ有効で、再起動時に解除されます。詳細追跡はログ量とフレーム時間を増加させます。",
        "settings.plugin_trace": "プラグイン呼び出し追跡（高負荷、30 秒）", "settings.plugin_trace_desc": "ネイティブプラグインの呼び出しと失敗境界を一時的に記録します",
        "settings.console_log": "旧コンソールログファイル", "settings.console_log_desc": "今回の実行ではエンジン出力をローカルログファイルにも書き込みます",
        "settings.trace_log": "完全 Trace ログ（高負荷、30 秒）", "settings.trace_log_desc": "最も詳細な spdlog trace 出力を一時的に有効にします",
        "settings.export_tjs": "TJS スクリプトを書き出す", "settings.export_tjs_desc": "今回の実行で XP3 読み込み時に逆アセンブル済みスクリプトを書き出します",
        "profile.off": "オフ", "profile.baseline": "基本", "profile.input": "入力", "profile.render": "描画", "profile.storage": "ストレージ", "profile.script": "スクリプト", "profile.audio": "音声", "profile.video": "動画", "profile.plugin": "プラグイン", "profile.system": "システム", "profile.full": "完全（高負荷）",
        "overlay.off": "オフ", "overlay.summary": "簡易", "overlay.detail": "詳細",
        "debug.title": "ランタイムデバッガー", "debug.open": "ランタイムデバッグドロワーを開く", "debug.tab.overview": "概要", "debug.tab.events": "イベント", "debug.tab.logs": "ログ", "debug.tab.input": "入力", "debug.tab.plugins": "プラグイン",
        "debug.action.mark": "問題をマーク", "debug.action.slow": "次の遅いフレームを取得", "debug.action.snapshot": "状態スナップショット", "debug.action.screenshot": "スクリーンショット", "debug.action.self_check": "セルフチェック", "debug.action.copy": "概要をコピー", "debug.action.export": "ZIP を書き出す",
        "debug.filter.subsystem": "サブシステムで絞り込み", "debug.filter.search": "ログを検索", "debug.logs.pause": "一時停止", "debug.logs.resume": "再開", "debug.logs.copy": "コピー", "debug.logs.clear": "消去",
        "debug.marker.user_issue": "一般的な問題", "debug.marker.slow_frame": "遅いフレーム", "debug.marker.input_issue": "入力の問題", "debug.marker.visual_issue": "表示の問題", "debug.marker.audio_issue": "音声の問題", "debug.marker.loading_issue": "読み込みの問題",
        "debug.filter.value.all": "すべて", "debug.filter.value.info": "情報", "debug.filter.value.warning": "警告", "debug.filter.value.error": "エラー", "debug.value.yes": "はい", "debug.value.no": "いいえ",
        "debug.input.visualize": "タッチとヒット位置を画面に表示", "debug.input.last": "直近のイベント", "debug.input.target": "ヒットしたコントロール",
        "debug.advanced.plugin": "プラグイン追跡", "debug.advanced.full": "完全追跡", "debug.advanced.console": "コンソールファイル", "debug.advanced.tjs": "TJS 書き出し",
        "debug.metric.frame": "フレームレート", "debug.metric.renderer": "レンダラー", "debug.metric.directory": "セッションディレクトリ", "debug.empty.events": "条件に一致するイベントはありません", "debug.empty.logs": "条件に一致するログはありません",
        "debug.overview.percentiles": "P50 %.2f ms  P95 %.2f ms  P99 %.2f ms  最大 %.2f ms", "debug.overview.phases": "C++ tick %.2f ms  Godot 更新 %.2f ms  フレーム %.2f ms", "debug.overview.render": "テクスチャ %s  サーフェス %s  フォールバック %s", "debug.overview.memory": "メモリ：App %s  システム空き/合計 %s / %s  キャッシュ %s", "debug.overview.memory_extended": "ピーク %s  余裕 %s  Godot %s  GPU（推定）%s（テクスチャ %s / バッファ %s）", "debug.overview.counts": "エラー %d  破棄イベント %d  マーカー %d",
        "debug.input.primary_counts": "受信 %d  転送 %d  ブロック %d", "debug.input.secondary_counts": "間引き %d  ビジー %d  範囲外 %d  抑制 %d", "debug.input.active_count": "有効なポインター %d",
        "debug.plugins.counts": "読み込み %d  失敗 %d  フォールバック %d  欠落 %d", "debug.plugins.calls": "メソッド呼び出し %d  プロパティ呼び出し %d", "debug.plugins.loaded": "読み込み済み：%s", "debug.plugins.failed": "失敗：%s", "debug.plugins.fallback": "フォールバック：%s", "debug.plugins.missing": "欠落：%s",
        "debug.overhead": "収集負荷", "debug.overhead.low": "低", "debug.overhead.medium": "中", "debug.overhead.high": "高",
        "debug.result.marked": "問題をマークしました：%s（後 5 秒を収集中）", "debug.result.marker_limit": "このセッションは問題マーカーの上限 %s 件に達しました", "debug.result.snapshot": "状態を保存しました：%s", "debug.result.screenshot": "スクリーンショットを保存しました：%s", "debug.result.exported": "診断パッケージを書き出しました：%s", "debug.result.copied": "診断概要をコピーしました", "debug.result.slow_armed": "しきい値を超える次のフレームを待機中", "debug.result.self_check": "セルフチェック：%s", "debug.result.unavailable": "有効な診断セッションがありません",
    },
    "ko": {
        "settings.section.diagnostics": "진단", "settings.section.compatibility": "호환성", "settings.section.advanced": "고급 개발 도구",
        "settings.diagnostic_profile": "진단 모드", "settings.diagnostic_profile_desc": "수집할 증거 범위를 한 프로필로 제어합니다. Baseline은 저비용이며 Full은 고비용 단기 실행용입니다.",
        "settings.debug_overlay": "디버그 오버레이", "settings.debug_overlay_desc": "게임 화면에 간단하거나 자세한 실시간 성능 요약을 표시합니다",
        "settings.error_dialog_logs": "오류 컨텍스트 첨부", "settings.error_dialog_logs_desc": "실제 오류 대화상자에 최근 로그 20줄을 첨부합니다",
        "settings.plugin_load_mode": "플러그인 로드 범위", "settings.plugin_load_mode_desc": "핵심 호환은 일반 플러그인만 로드하고 전체 호환은 기존 전체 등록 경로를 유지합니다",
        "settings.plugin_load.core": "핵심 호환", "settings.plugin_load.all": "전체 호환",
        "settings.mock": "누락 플러그인 호환", "settings.mock_desc": "누락 플러그인에 호환 객체를 반환합니다. 끄면 실제 누락 오류를 확인할 수 있습니다.",
        "settings.advanced_desc": "아래 스위치는 이번 실행에만 적용되며 재시작하면 꺼집니다. 상세 추적은 로그 양과 프레임 시간을 늘립니다.",
        "settings.plugin_trace": "플러그인 호출 추적(고비용, 30초)", "settings.plugin_trace_desc": "모든 네이티브 플러그인 호출과 실패 경계를 잠시 기록합니다",
        "settings.console_log": "레거시 콘솔 로그 파일", "settings.console_log_desc": "이번 실행에서 엔진 출력을 로컬 로그 파일에도 기록합니다",
        "settings.trace_log": "전체 Trace 로그(고비용, 30초)", "settings.trace_log_desc": "가장 자세한 spdlog trace 출력을 잠시 활성화합니다",
        "settings.export_tjs": "TJS 스크립트 내보내기", "settings.export_tjs_desc": "이번 실행에서 XP3 로드 중 역어셈블된 스크립트를 내보냅니다",
        "profile.off": "끔", "profile.baseline": "기본", "profile.input": "입력", "profile.render": "렌더링", "profile.storage": "저장소", "profile.script": "스크립트", "profile.audio": "오디오", "profile.video": "비디오", "profile.plugin": "플러그인", "profile.system": "시스템", "profile.full": "전체(고비용)",
        "overlay.off": "끔", "overlay.summary": "간단히", "overlay.detail": "자세히",
        "debug.title": "런타임 디버거", "debug.open": "런타임 디버그 서랍 열기", "debug.tab.overview": "개요", "debug.tab.events": "이벤트", "debug.tab.logs": "로그", "debug.tab.input": "입력", "debug.tab.plugins": "플러그인",
        "debug.action.mark": "문제 표시", "debug.action.slow": "다음 느린 프레임 캡처", "debug.action.snapshot": "상태 스냅샷", "debug.action.screenshot": "스크린샷", "debug.action.self_check": "자체 검사", "debug.action.copy": "요약 복사", "debug.action.export": "ZIP 내보내기",
        "debug.filter.subsystem": "하위 시스템 필터", "debug.filter.search": "로그 검색", "debug.logs.pause": "일시정지", "debug.logs.resume": "계속", "debug.logs.copy": "복사", "debug.logs.clear": "지우기",
        "debug.marker.user_issue": "일반 문제", "debug.marker.slow_frame": "느린 프레임", "debug.marker.input_issue": "입력 문제", "debug.marker.visual_issue": "화면 문제", "debug.marker.audio_issue": "오디오 문제", "debug.marker.loading_issue": "로딩 문제",
        "debug.filter.value.all": "전체", "debug.filter.value.info": "정보", "debug.filter.value.warning": "경고", "debug.filter.value.error": "오류", "debug.value.yes": "예", "debug.value.no": "아니요",
        "debug.input.visualize": "화면에 터치와 적중 위치 표시", "debug.input.last": "최근 이벤트", "debug.input.target": "적중 컨트롤",
        "debug.advanced.plugin": "플러그인 추적", "debug.advanced.full": "전체 추적", "debug.advanced.console": "콘솔 파일", "debug.advanced.tjs": "TJS 내보내기",
        "debug.metric.frame": "프레임률", "debug.metric.renderer": "렌더러", "debug.metric.directory": "세션 디렉터리", "debug.empty.events": "현재 필터와 일치하는 이벤트가 없습니다", "debug.empty.logs": "현재 필터와 일치하는 로그가 없습니다",
        "debug.overview.percentiles": "P50 %.2f ms  P95 %.2f ms  P99 %.2f ms  최대 %.2f ms", "debug.overview.phases": "C++ tick %.2f ms  Godot 업데이트 %.2f ms  프레임 %.2f ms", "debug.overview.render": "텍스처 %s  화면 %s  폴백 %s", "debug.overview.memory": "메모리: 앱 %s  시스템 여유/전체 %s / %s  캐시 %s", "debug.overview.memory_extended": "최고치 %s  여유 한도 %s  Godot %s  GPU(추정) %s(텍스처 %s / 버퍼 %s)", "debug.overview.counts": "오류 %d  폐기 이벤트 %d  문제 표시 %d",
        "debug.input.primary_counts": "수신 %d  전달 %d  차단 %d", "debug.input.secondary_counts": "제한 %d  사용 중 %d  범위 밖 %d  억제 %d", "debug.input.active_count": "활성 포인터 %d",
        "debug.plugins.counts": "로드 %d  실패 %d  폴백 %d  누락 %d", "debug.plugins.calls": "메서드 호출 %d  속성 호출 %d", "debug.plugins.loaded": "로드됨: %s", "debug.plugins.failed": "실패: %s", "debug.plugins.fallback": "폴백: %s", "debug.plugins.missing": "누락: %s",
        "debug.overhead": "수집 비용", "debug.overhead.low": "낮음", "debug.overhead.medium": "중간", "debug.overhead.high": "높음",
        "debug.result.marked": "문제를 표시했습니다: %s(이후 5초 수집 중)", "debug.result.marker_limit": "이 세션은 문제 표시 한도 %s개에 도달했습니다", "debug.result.snapshot": "상태 스냅샷 저장: %s", "debug.result.screenshot": "스크린샷 저장: %s", "debug.result.exported": "진단 패키지 내보냄: %s", "debug.result.copied": "진단 요약을 복사했습니다", "debug.result.slow_armed": "임계값을 넘는 다음 프레임을 기다리는 중", "debug.result.self_check": "자체 검사: %s", "debug.result.unavailable": "활성 진단 세션이 없습니다",
    },
}

static func get_text(language: String, key: String) -> String:
    var language_table: Dictionary = TEXT.get(language, TEXT["en"])
    if language_table.has(key):
        return String(language_table[key])
    return String(TEXT["en"].get(key, key))

static func has_key(key: String) -> bool:
    return TEXT["en"].has(key)

static func validate() -> PackedStringArray:
    var missing := PackedStringArray()
    var keys: Array = TEXT["en"].keys()
    for language in TEXT:
        for key in keys:
            if not TEXT[language].has(key):
                missing.append("%s:%s" % [language, key])
    return missing
