#ifndef AETHERKIRI_LEGACY_ENGINE_API_RENAME_H_
#define AETHERKIRI_LEGACY_ENGINE_API_RENAME_H_

#define engine_get_runtime_api_version engine_legacy_get_runtime_api_version
#define engine_create engine_legacy_create
#define engine_destroy engine_legacy_destroy
#define engine_open_game engine_legacy_open_game
#define engine_open_game_async engine_legacy_open_game_async
#define engine_get_startup_state engine_legacy_get_startup_state
#define engine_drain_startup_logs engine_legacy_drain_startup_logs
#define engine_tick engine_legacy_tick
#define engine_pause engine_legacy_pause
#define engine_resume engine_legacy_resume
#define engine_set_option engine_legacy_set_option
#define engine_set_surface_size engine_legacy_set_surface_size
#define engine_get_frame_desc engine_legacy_get_frame_desc
#define engine_read_frame_rgba engine_legacy_read_frame_rgba
#define engine_media_open engine_legacy_media_open
#define engine_media_destroy engine_legacy_media_destroy
#define engine_media_play engine_legacy_media_play
#define engine_media_pause engine_legacy_media_pause
#define engine_media_seek engine_legacy_media_seek
#define engine_media_set_rate engine_legacy_media_set_rate
#define engine_media_get_state engine_legacy_media_get_state
#define engine_media_get_subtitle_tracks_json \
  engine_legacy_media_get_subtitle_tracks_json
#define engine_media_extract_subtitle engine_legacy_media_extract_subtitle
#define engine_media_read_frame_rgba engine_legacy_media_read_frame_rgba
#define engine_get_godot_native_frame_texture \
  engine_legacy_get_godot_native_frame_texture
#define engine_get_host_native_window engine_legacy_get_host_native_window
#define engine_get_host_native_view engine_legacy_get_host_native_view
#define engine_send_input engine_legacy_send_input
#define engine_get_text_input_state engine_legacy_get_text_input_state
#define engine_copy_text_input_text engine_legacy_copy_text_input_text
#define engine_get_main_menu_json engine_legacy_get_main_menu_json
#define engine_activate_menu_item engine_legacy_activate_menu_item
#define engine_set_render_target_iosurface \
  engine_legacy_set_render_target_iosurface
#define engine_set_render_target_surface engine_legacy_set_render_target_surface
#define engine_get_frame_rendered_flag engine_legacy_get_frame_rendered_flag
#define engine_get_renderer_info engine_legacy_get_renderer_info
#define engine_get_memory_stats engine_legacy_get_memory_stats
#define engine_get_plugin_debug_info engine_legacy_get_plugin_debug_info
#define engine_set_diagnostic_config engine_legacy_set_diagnostic_config
#define engine_mark_diagnostic_event engine_legacy_mark_diagnostic_event
#define engine_drain_diagnostic_events engine_legacy_drain_diagnostic_events
#define engine_get_last_error engine_legacy_get_last_error

#endif  /* AETHERKIRI_LEGACY_ENGINE_API_RENAME_H_ */
